In [9]:
import numpy as np
import torch

In [69]:


image_t = torch.rand((10,10))
x_index = torch.zeros_like(image_t)
for i in range(10):
    x_index[i,:] = torch.arange(0,10)
# x_index = x_index.to(dtype=torch.int)
y_index = x_index.transpose(0,1)
print(y_index)
print((x_index - 10 / 2)**2 + (y_index - 10 / 2)**2)
radius = torch.sqrt((x_index - 10 / 2)**2 + (y_index - 10 / 2)**2)
radius = radius.to(dtype=torch.int)
radius = torch.flatten(radius)
radius_bin = torch.bincount(radius)
ten_bin = torch.bincount(radius, image_t.flatten())
radial_prof = ten_bin / (radius_bin + 1e-10)
# radius = radius.view(128*128)
print(radial_prof)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
        [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])
tensor([[50., 41., 34., 29., 26., 25., 26., 29., 34., 41.],
        [41., 32., 25., 20., 17., 16., 17., 20., 25., 32.],
        [34., 25., 18., 13., 10.,  9., 10., 13., 18., 25.],
        [29., 20., 13.,  8.,  5.,  4.,  5.,  8., 13., 20.],
        [26., 17., 10.,  5.,  2.,  1.,  2.,  5., 10., 17.],
        [25., 16.,  9.,  4.,  1.,  0.,  1.,  4.,  9., 16.],
        [26., 17., 10.,  5.,  2.,  1.,  2.,  5., 10., 17.],
        [29., 20., 13.,  8.,  5.,  4.,  5.,  8., 13., 20.],
        [34., 25., 

In [82]:
x = torch.empty()

TypeError: empty() received an invalid combination of arguments - got (), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.memory_format memory_format, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


In [80]:
y = torch.rand(5)
for i in range(5):
    y[i] = x

RuntimeError: expand(torch.FloatTensor{[10]}, size=[]): the number of sizes provided (0) must be greater or equal to the number of dimensions in the tensor (1)

In [70]:
# Calculate the indices from the image
image = image_t.numpy()
H, W = image.shape[0], image.shape[1]
y, x = np.indices([H, W])
# print(x)
# print(y)
# print(y.shape, x.shape)
# print((x - H / 2)**2 + (y - W / 2)**2)
radius = np.sqrt((x - H / 2)**2 + (y - W / 2)**2)
# print(radius)
# print(radius.shape)

radius = radius.astype(np.int).ravel()
print(radius)
nr = np.bincount(radius)
print(nr)
tbin = np.bincount(radius, image.ravel())
print(tbin)
radial_prof = tbin / (nr + 1e-10)
print(radial_prof)
# return radial_prof[
#     1:
#     -2]  

[7 6 5 5 5 5 5 5 5 6 6 5 5 4 4 4 4 4 5 5 5 5 4 3 3 3 3 3 4 5 5 4 3 2 2 2 2
 2 3 4 5 4 3 2 1 1 1 2 3 4 5 4 3 2 1 0 1 2 3 4 5 4 3 2 1 1 1 2 3 4 5 4 3 2
 2 2 2 2 3 4 5 5 4 3 3 3 3 3 4 5 6 5 5 4 4 4 4 4 5 5]
[ 1  8 16 20 24 26  4  1]
[ 0.89038849  3.98525614  7.61187625  8.86322182 11.49624634 16.61291754
  1.32034212  0.93878275]
[0.89038849 0.49815702 0.47574227 0.44316109 0.47901026 0.63895837
 0.33008553 0.93878275]


/tmp/ipykernel_1582786/2737864010.py:13: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  radius = radius.astype(np.int).ravel()
